insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'New Year’s Day (substitute day)', '2021-01-01')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Good Friday', '2021-03-02')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Easter Monday', '2021-03-05')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Early May bank holiday', '2021-05-03')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Spring bank holiday', '2021-05-31')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Summer bank holiday', '2021-08-30')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Christmas Day (substitute day)', '2021-12-27')
insert into holidays_relational (country, province, year, label, holiday) values ('UK', 'ALL', 2021, 'Boxing Day (substitute day)', '2021-12-28')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'New Year’s Day (1 January)', '2021-01-01')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Saint Patrick’s Day (17 March)', '2021-03-17')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Easter Monday', '2021-04-05')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Easter Monday', '2021-05-03')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'First Monday in June', '2021-06-07')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'First Monday in August', '2021-08-02')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Last Monday in October', '2021-10-25')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Christmas Day (25 December)', '2021-12-25')
insert into holidays_relational (country, province, year, label, holiday) values ('IE', 'ALL', 2021, 'Saint Stephen’s Day (26 December)', '2021-12-26')

insert into holidays_hybrid (country, province, year, json) values ('UK', 'ALL', 2021, '{"holidays": [{"label": "New Year’s Day (substitute day)", "year": "2021-01-01"},{"label": "Good Friday", "year": "2021-03-02"},{"label": "Easter Monday", "year": "2021-03-05"},{"label": "Early May bank holiday", "year": "2021-05-03"},{"label": "Early May bank holiday", "year": "2021-05-31"},{"label": "Summer bank holiday", "year": "2021-08-30"},{"label": "Christmas Day (substitute day)", "year": "2021-12-27"},{"label": "Boxing Day (substitute day)", "year": "2021-12-28"}]}')
insert into holidays_hybrid (country, province, year, json) values ('IE', 'ALL', 2021, '{"holidays": [{"label": "New Year’s Day (substitute day)", "year": "2021-01-01"},{"label": "Good Friday", "year": "2021-03-02"},{"label": "Easter Monday", "year": "2021-03-05"},{"label": "Early May bank holiday", "year": "2021-05-03"},{"label": "Early May bank holiday", "year": "2021-05-31"},{"label": "Summer bank holiday", "year": "2021-08-30"},{"label": "Christmas Day (substitute day)", "year": "2021-12-27"},{"label": "Boxing Day (substitute day)", "year": "2021-12-28"}]}')
