-- Table: public.holidays_hybrid

-- DROP TABLE public.holidays_hybrid;

CREATE TABLE public.holidays_hybrid
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    country character varying(255) COLLATE pg_catalog."default",
    province character varying(255) COLLATE pg_catalog."default",
    year integer NOT NULL,
    json jsonb,
    CONSTRAINT holidays_hybrid_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.holidays_hybrid
    OWNER to "";